[book]
title       = "dprint-plugin-svg"
description = "Configuration reference for the dprint SVG formatting plugin"
authors     = ["Kaj Kowalski"]
language    = "en"

[build]
build-dir = "book"

[output.html]
default-theme        = "navy"
preferred-dark-theme = "navy"
cname                = "dprint-svg.kjanat.com"
git-repository-url   = "https://github.com/kjanat/dprint-plugin-svg"
edit-url-template    = "https://github.com/kjanat/dprint-plugin-svg/edit/master/docs/src/{path}"
